name: Build

# Author: @MikeRalphson
# Issue : n/a
# Desc  : This workflow runs a build on pushes to main and prs

# run this on push to main
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # checkout repo content
    - uses: actions/setup-node@v1 # setup Node.js
      with:
        node-version: 16
    - name: Install deps
      run: npm i
    - name: Run lint
      run: npm run lint
    - name: Run sass
      run: npm run sass
    - name: Run build
      run: npm run build -- --pathprefix=/mdl-catalog-ui/
